import type { Metadata } from "next";
import { Do_Hyeon } from "next/font/google";
import "./globals.css";
import React from "react";

const do_Hyeon = Do_Hyeon({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Bum_Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={do_Hyeon.className}>{children}</body>
    </html>
  );
}
