import type { Metadata } from "next";
import { Gowun_Dodum } from "next/font/google";
import Header from "../components/header";
import RecoilRootWrapper from "./recoilWrapper";
import "./globals.css";
import React from "react";

const gowun_Dodum = Gowun_Dodum({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Bum_Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={gowun_Dodum.className}>
        <RecoilRootWrapper>
          {" "}
          <Header />
          <main className="bg-cover bg-center bg-[url('/background-main.png')] flex min-h-screen flex-col items-center justify-between relative z-0">
            {children}
          </main>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
