name: Deploy to Vercel

on:
  schedule:
    - cron: "0 */4 * * *" # Every 4 hours
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Trigger Vercel Deploy Hook
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: curl -X POST $VERCEL_DEPLOY_HOOK_URL
